# Generated by Django 3.0.11 on 2021-02-17 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userlibrary',
            options={'verbose_name_plural': 'UserLibraries'},
        ),
    ]
